name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v3
      - run: npm i
      - run: npm run build
